FROM pytorch/pytorch:1.4-cuda10.1-cudnn7-runtime

ARG DATASET
ARG MODEL_TYPE

# Install python packages
RUN pip install --no-cache-dir absl-py requests regex

COPY configs/requirements-$MODEL_TYPE.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

COPY models/$MODEL_TYPE/$DATASET /models/$DATASET
COPY resources/$DATASET /resources/$DATASET

ENV DATASET=$DATASET
ENV MODEL_TYPE=$MODEL_TYPE

COPY workspace /workspace
COPY entrypoint.sh /workspace/entrypoint.sh
RUN chmod a+x /workspace/entrypoint.sh

WORKDIR /workspace
